# Generated by Django 5.0.6 on 2024-07-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('passport_photo', models.ImageField(upload_to='passport_photo/')),
                ('prava_photo', models.ImageField(upload_to='prava_photo/')),
                ('balance', models.PositiveIntegerField(blank=True, default=50000, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
    ]
