# Generated by Django 5.0.6 on 2024-07-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telegram_id',
            field=models.CharField(default=2, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
