# Generated by Django 5.0.6 on 2024-07-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='prava_photo',
            field=models.ImageField(default=1, upload_to='prava_photo/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='passport_photo',
            field=models.ImageField(upload_to='passport_photo/'),
        ),
    ]
