# Generated by Django 5.0.6 on 2024-07-27 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_prava_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='balance',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
