# Generated by Django 5.0.6 on 2024-07-29 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
        ('users', '0002_userprofile_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='getrequest',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
            preserve_default=False,
        ),
    ]
