# Generated by Django 5.0.6 on 2024-07-29 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_getrequest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='getrequest',
            name='where',
        ),
        migrations.RemoveField(
            model_name='getrequest',
            name='whereTo',
        ),
    ]
